//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.0
//     from Assets/Plugins/AbuInput/AbuInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace abunity.Input
{
    public partial class @AbuInputAction: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @AbuInputAction()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""AbuInputAction"",
    ""maps"": [
        {
            ""name"": ""abuMap"",
            ""id"": ""7b02076c-a1b9-4d82-ad20-f4a3a97ca4a7"",
            ""actions"": [
                {
                    ""name"": ""ActionBottomRow1"",
                    ""type"": ""Button"",
                    ""id"": ""69e76ba4-548c-4dd6-a976-e3400f4c9a82"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionBottomRow2"",
                    ""type"": ""Button"",
                    ""id"": ""1529bf63-19ff-4ff7-82c7-9d9bc7f2b918"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionTopRow1"",
                    ""type"": ""Button"",
                    ""id"": ""748ae36e-4a60-4af9-afaa-3dd5f4b7466f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionTopRow2"",
                    ""type"": ""Button"",
                    ""id"": ""18c3ce0b-99e7-47c9-9643-1e3c999925eb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadUp"",
                    ""type"": ""Button"",
                    ""id"": ""7a84b8b9-0ce1-4b7c-8e22-1d7aa160d158"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadDown"",
                    ""type"": ""Button"",
                    ""id"": ""0663aaf4-fc1f-43d8-8ead-11e14c65bbe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadLeft"",
                    ""type"": ""Button"",
                    ""id"": ""6b62d143-3972-4350-a6c1-006f8b92c73c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DPadRight"",
                    ""type"": ""Button"",
                    ""id"": ""3e9b0b21-4c78-4587-8ce0-0ca87e08b561"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickUp"",
                    ""type"": ""Button"",
                    ""id"": ""36abad5d-6244-4a94-a68d-1a2df2c83592"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickDown"",
                    ""type"": ""Button"",
                    ""id"": ""cacbf251-d971-4d3c-8694-efec5364dce2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickLeft"",
                    ""type"": ""Button"",
                    ""id"": ""80cbe377-5e0d-41d4-b4fe-bf9366bee824"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickRight"",
                    ""type"": ""Button"",
                    ""id"": ""ff0dc250-5dbe-4423-9dea-1cc319109a18"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickButton"",
                    ""type"": ""Button"",
                    ""id"": ""ad14cd58-e279-41ce-8196-600bc6df3e73"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftStickHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""472f26a8-fcd4-4707-816e-010187cf9793"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftStickVertical"",
                    ""type"": ""Value"",
                    ""id"": ""4dc0890f-cf50-473c-96bf-2ae3a377c356"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""type"": ""Value"",
                    ""id"": ""43a8e930-4dc9-4047-b525-e9c10cb4d6da"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickUp"",
                    ""type"": ""Value"",
                    ""id"": ""0ebaf402-4be2-4abb-abe2-a8956e0f4523"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickDown"",
                    ""type"": ""Button"",
                    ""id"": ""b952548c-7fd1-4061-b2d4-c0010c5b9a51"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickLeft"",
                    ""type"": ""Button"",
                    ""id"": ""22d73c12-ca0a-4397-b99c-a1e87650b68b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickRight"",
                    ""type"": ""Button"",
                    ""id"": ""391c366b-b397-4e89-8015-cdfc9c6bf3f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickButton"",
                    ""type"": ""Button"",
                    ""id"": ""715c1db5-d40c-423f-b358-17101755f272"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightStickHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""7fd55b70-9d95-4565-bc5c-874b608a481c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStickVertical"",
                    ""type"": ""Value"",
                    ""id"": ""b6139fd2-204a-49c4-849c-0a4a7c344072"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RightStick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6813a55f-aeed-403e-aed7-cb3da1f77d44"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftBumper"",
                    ""type"": ""Button"",
                    ""id"": ""f827baea-6098-45b2-8351-7548ab97792e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightBumper"",
                    ""type"": ""Button"",
                    ""id"": ""0f176c7d-ef71-4423-aba3-03fd30b15c44"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""629ce127-5a8b-4919-b270-158cd062f2de"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightTrigger"",
                    ""type"": ""Button"",
                    ""id"": ""442e9e0f-3136-4f42-b3c7-e3aa28ff438c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""a8248806-92cf-4cfc-9db8-db133aa6a2c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Start"",
                    ""type"": ""Button"",
                    ""id"": ""517f09ee-b46b-4291-9876-90da2b67a86b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""747d46d0-833d-4caf-a534-456b096fdedc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3114220f-c7e7-42a7-9a21-58cc75430b51"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75f03e60-4d9a-4953-aaaa-c23ad99ae03a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bbc7f06-7a93-4ae8-96d3-bf29bf1dd130"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""abcccaf3-ebf5-4961-b3b7-81b81dcb33eb"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e116da7-6d0f-4315-be8b-a964062f53f3"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""546dd6d0-61d0-40e2-80f3-2b5b658681ca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cece383d-bc8c-4005-8628-404e7c53d040"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DPadRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c6aa9f1-5af4-4b08-bc23-18fc51c9e23b"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b5575fa-40b5-4e43-a97d-e1b1347affd2"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBottomRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""491e3e89-729b-4693-be53-4bb38dd84e2f"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionBottomRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae602334-3a13-4ce8-8774-2fb00d96b059"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27a1950c-4e4e-493b-9f58-7b4ba633be3d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTopRow1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19e57fea-52d1-4ec9-940c-311450c0e565"",
                    ""path"": ""<Keyboard>/leftCtrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""934fba5e-36f8-4a96-b48c-ca01742d7bb5"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionTopRow2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""02e12d0f-1e61-44bf-8830-6215edc28cfa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ce8b6c1-43b7-4b62-8335-de3a49496384"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f047148-7b36-4518-8062-3eb6d992a8cc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29e5eba7-fbe8-417a-be49-8989d14f484a"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9da30431-eeb3-46a0-a0bb-cb1ccbc70633"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""862e0cb6-fc80-4d2b-b97b-cb5090afcc8e"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e459dacd-fb48-46ea-932c-ab47abaafb1e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""032e4107-6243-4e66-8b2c-bd71ba422245"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fa8ad83-70a9-4235-bdda-e5dbc15a05a6"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f815061f-c81b-4a0e-8169-9f778d9137eb"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""29a9acdb-ae05-4ab7-968c-2b784b85c2e0"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3f80cd8-18d8-4deb-94ce-f04da25050be"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3660c279-b515-489d-8cce-d85c6707d3e4"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74b18e8b-bacf-4750-827f-e72783314313"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightBumper"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be863a96-8cc7-4325-9ceb-a7d747491ca6"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9e00331-51a1-42a7-ac1b-0c5ddbec378e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightTrigger"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66d53226-7d16-4856-bf1b-344ba6057d93"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aff520fe-c179-43b8-84fa-87ce130ff6e7"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e6df95f-a3dd-49bd-93d0-3d9fb8330dd9"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bb838a1-c3c9-48b8-ba0f-6ca84cc4df8f"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51907b64-a438-4266-95f7-95473d1cc8c7"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Start"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""8aa49af8-9b3f-4f68-bea2-96f43b66735d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fe7b961d-4d41-4477-9a32-57b8d0df1c34"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0d8de00a-a6c9-4375-85f9-2a4102e6d6fb"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ba43e208-bbfc-4209-a6c5-7c31368262da"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""4913c4c3-d71a-4a86-b226-63cc6dd8f7f7"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVertical"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""417d9569-9ba0-4c85-b78b-70b876bc266b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""8c7ba6bb-047a-4037-981d-67122bc317ae"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d11e4a54-b5b0-4100-b37f-45e10aaddc5d"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""4c2c37a9-4473-4ee3-b5fd-772ded1cab50"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bc51b182-7d73-48ce-af58-c6d19a8de985"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""30546607-cc49-445f-81bb-6fed7408a59d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""31a71a70-49f8-4614-b351-10e815460ed0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""34f646a6-0a20-4776-ba00-fe454bca61de"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""93fc46ec-3630-4815-a077-db0aac4f4661"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92c93324-efb1-4ef0-b046-916174660c20"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""898208c5-24b5-4555-b200-309f0370900f"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e155674-1059-4058-849e-e5328f085c53"",
                    ""path"": ""<Mouse>/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1908e319-6e3a-4b80-a6f6-4732ad8d3608"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStickVertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""801bd889-87da-4677-98f8-4f41bc61a1c1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""965cf1e7-4725-40e6-bc03-0986ae4dc7d6"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightStick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // abuMap
            m_abuMap = asset.FindActionMap("abuMap", throwIfNotFound: true);
            m_abuMap_ActionBottomRow1 = m_abuMap.FindAction("ActionBottomRow1", throwIfNotFound: true);
            m_abuMap_ActionBottomRow2 = m_abuMap.FindAction("ActionBottomRow2", throwIfNotFound: true);
            m_abuMap_ActionTopRow1 = m_abuMap.FindAction("ActionTopRow1", throwIfNotFound: true);
            m_abuMap_ActionTopRow2 = m_abuMap.FindAction("ActionTopRow2", throwIfNotFound: true);
            m_abuMap_DPadUp = m_abuMap.FindAction("DPadUp", throwIfNotFound: true);
            m_abuMap_DPadDown = m_abuMap.FindAction("DPadDown", throwIfNotFound: true);
            m_abuMap_DPadLeft = m_abuMap.FindAction("DPadLeft", throwIfNotFound: true);
            m_abuMap_DPadRight = m_abuMap.FindAction("DPadRight", throwIfNotFound: true);
            m_abuMap_LeftStickUp = m_abuMap.FindAction("LeftStickUp", throwIfNotFound: true);
            m_abuMap_LeftStickDown = m_abuMap.FindAction("LeftStickDown", throwIfNotFound: true);
            m_abuMap_LeftStickLeft = m_abuMap.FindAction("LeftStickLeft", throwIfNotFound: true);
            m_abuMap_LeftStickRight = m_abuMap.FindAction("LeftStickRight", throwIfNotFound: true);
            m_abuMap_LeftStickButton = m_abuMap.FindAction("LeftStickButton", throwIfNotFound: true);
            m_abuMap_LeftStickHorizontal = m_abuMap.FindAction("LeftStickHorizontal", throwIfNotFound: true);
            m_abuMap_LeftStickVertical = m_abuMap.FindAction("LeftStickVertical", throwIfNotFound: true);
            m_abuMap_LeftStick = m_abuMap.FindAction("LeftStick", throwIfNotFound: true);
            m_abuMap_RightStickUp = m_abuMap.FindAction("RightStickUp", throwIfNotFound: true);
            m_abuMap_RightStickDown = m_abuMap.FindAction("RightStickDown", throwIfNotFound: true);
            m_abuMap_RightStickLeft = m_abuMap.FindAction("RightStickLeft", throwIfNotFound: true);
            m_abuMap_RightStickRight = m_abuMap.FindAction("RightStickRight", throwIfNotFound: true);
            m_abuMap_RightStickButton = m_abuMap.FindAction("RightStickButton", throwIfNotFound: true);
            m_abuMap_RightStickHorizontal = m_abuMap.FindAction("RightStickHorizontal", throwIfNotFound: true);
            m_abuMap_RightStickVertical = m_abuMap.FindAction("RightStickVertical", throwIfNotFound: true);
            m_abuMap_RightStick = m_abuMap.FindAction("RightStick", throwIfNotFound: true);
            m_abuMap_LeftBumper = m_abuMap.FindAction("LeftBumper", throwIfNotFound: true);
            m_abuMap_RightBumper = m_abuMap.FindAction("RightBumper", throwIfNotFound: true);
            m_abuMap_LeftTrigger = m_abuMap.FindAction("LeftTrigger", throwIfNotFound: true);
            m_abuMap_RightTrigger = m_abuMap.FindAction("RightTrigger", throwIfNotFound: true);
            m_abuMap_Select = m_abuMap.FindAction("Select", throwIfNotFound: true);
            m_abuMap_Start = m_abuMap.FindAction("Start", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // abuMap
        private readonly InputActionMap m_abuMap;
        private List<IAbuMapActions> m_AbuMapActionsCallbackInterfaces = new List<IAbuMapActions>();
        private readonly InputAction m_abuMap_ActionBottomRow1;
        private readonly InputAction m_abuMap_ActionBottomRow2;
        private readonly InputAction m_abuMap_ActionTopRow1;
        private readonly InputAction m_abuMap_ActionTopRow2;
        private readonly InputAction m_abuMap_DPadUp;
        private readonly InputAction m_abuMap_DPadDown;
        private readonly InputAction m_abuMap_DPadLeft;
        private readonly InputAction m_abuMap_DPadRight;
        private readonly InputAction m_abuMap_LeftStickUp;
        private readonly InputAction m_abuMap_LeftStickDown;
        private readonly InputAction m_abuMap_LeftStickLeft;
        private readonly InputAction m_abuMap_LeftStickRight;
        private readonly InputAction m_abuMap_LeftStickButton;
        private readonly InputAction m_abuMap_LeftStickHorizontal;
        private readonly InputAction m_abuMap_LeftStickVertical;
        private readonly InputAction m_abuMap_LeftStick;
        private readonly InputAction m_abuMap_RightStickUp;
        private readonly InputAction m_abuMap_RightStickDown;
        private readonly InputAction m_abuMap_RightStickLeft;
        private readonly InputAction m_abuMap_RightStickRight;
        private readonly InputAction m_abuMap_RightStickButton;
        private readonly InputAction m_abuMap_RightStickHorizontal;
        private readonly InputAction m_abuMap_RightStickVertical;
        private readonly InputAction m_abuMap_RightStick;
        private readonly InputAction m_abuMap_LeftBumper;
        private readonly InputAction m_abuMap_RightBumper;
        private readonly InputAction m_abuMap_LeftTrigger;
        private readonly InputAction m_abuMap_RightTrigger;
        private readonly InputAction m_abuMap_Select;
        private readonly InputAction m_abuMap_Start;
        public struct AbuMapActions
        {
            private @AbuInputAction m_Wrapper;
            public AbuMapActions(@AbuInputAction wrapper) { m_Wrapper = wrapper; }
            public InputAction @ActionBottomRow1 => m_Wrapper.m_abuMap_ActionBottomRow1;
            public InputAction @ActionBottomRow2 => m_Wrapper.m_abuMap_ActionBottomRow2;
            public InputAction @ActionTopRow1 => m_Wrapper.m_abuMap_ActionTopRow1;
            public InputAction @ActionTopRow2 => m_Wrapper.m_abuMap_ActionTopRow2;
            public InputAction @DPadUp => m_Wrapper.m_abuMap_DPadUp;
            public InputAction @DPadDown => m_Wrapper.m_abuMap_DPadDown;
            public InputAction @DPadLeft => m_Wrapper.m_abuMap_DPadLeft;
            public InputAction @DPadRight => m_Wrapper.m_abuMap_DPadRight;
            public InputAction @LeftStickUp => m_Wrapper.m_abuMap_LeftStickUp;
            public InputAction @LeftStickDown => m_Wrapper.m_abuMap_LeftStickDown;
            public InputAction @LeftStickLeft => m_Wrapper.m_abuMap_LeftStickLeft;
            public InputAction @LeftStickRight => m_Wrapper.m_abuMap_LeftStickRight;
            public InputAction @LeftStickButton => m_Wrapper.m_abuMap_LeftStickButton;
            public InputAction @LeftStickHorizontal => m_Wrapper.m_abuMap_LeftStickHorizontal;
            public InputAction @LeftStickVertical => m_Wrapper.m_abuMap_LeftStickVertical;
            public InputAction @LeftStick => m_Wrapper.m_abuMap_LeftStick;
            public InputAction @RightStickUp => m_Wrapper.m_abuMap_RightStickUp;
            public InputAction @RightStickDown => m_Wrapper.m_abuMap_RightStickDown;
            public InputAction @RightStickLeft => m_Wrapper.m_abuMap_RightStickLeft;
            public InputAction @RightStickRight => m_Wrapper.m_abuMap_RightStickRight;
            public InputAction @RightStickButton => m_Wrapper.m_abuMap_RightStickButton;
            public InputAction @RightStickHorizontal => m_Wrapper.m_abuMap_RightStickHorizontal;
            public InputAction @RightStickVertical => m_Wrapper.m_abuMap_RightStickVertical;
            public InputAction @RightStick => m_Wrapper.m_abuMap_RightStick;
            public InputAction @LeftBumper => m_Wrapper.m_abuMap_LeftBumper;
            public InputAction @RightBumper => m_Wrapper.m_abuMap_RightBumper;
            public InputAction @LeftTrigger => m_Wrapper.m_abuMap_LeftTrigger;
            public InputAction @RightTrigger => m_Wrapper.m_abuMap_RightTrigger;
            public InputAction @Select => m_Wrapper.m_abuMap_Select;
            public InputAction @Start => m_Wrapper.m_abuMap_Start;
            public InputActionMap Get() { return m_Wrapper.m_abuMap; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(AbuMapActions set) { return set.Get(); }
            public void AddCallbacks(IAbuMapActions instance)
            {
                if (instance == null || m_Wrapper.m_AbuMapActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_AbuMapActionsCallbackInterfaces.Add(instance);
                @ActionBottomRow1.started += instance.OnActionBottomRow1;
                @ActionBottomRow1.performed += instance.OnActionBottomRow1;
                @ActionBottomRow1.canceled += instance.OnActionBottomRow1;
                @ActionBottomRow2.started += instance.OnActionBottomRow2;
                @ActionBottomRow2.performed += instance.OnActionBottomRow2;
                @ActionBottomRow2.canceled += instance.OnActionBottomRow2;
                @ActionTopRow1.started += instance.OnActionTopRow1;
                @ActionTopRow1.performed += instance.OnActionTopRow1;
                @ActionTopRow1.canceled += instance.OnActionTopRow1;
                @ActionTopRow2.started += instance.OnActionTopRow2;
                @ActionTopRow2.performed += instance.OnActionTopRow2;
                @ActionTopRow2.canceled += instance.OnActionTopRow2;
                @DPadUp.started += instance.OnDPadUp;
                @DPadUp.performed += instance.OnDPadUp;
                @DPadUp.canceled += instance.OnDPadUp;
                @DPadDown.started += instance.OnDPadDown;
                @DPadDown.performed += instance.OnDPadDown;
                @DPadDown.canceled += instance.OnDPadDown;
                @DPadLeft.started += instance.OnDPadLeft;
                @DPadLeft.performed += instance.OnDPadLeft;
                @DPadLeft.canceled += instance.OnDPadLeft;
                @DPadRight.started += instance.OnDPadRight;
                @DPadRight.performed += instance.OnDPadRight;
                @DPadRight.canceled += instance.OnDPadRight;
                @LeftStickUp.started += instance.OnLeftStickUp;
                @LeftStickUp.performed += instance.OnLeftStickUp;
                @LeftStickUp.canceled += instance.OnLeftStickUp;
                @LeftStickDown.started += instance.OnLeftStickDown;
                @LeftStickDown.performed += instance.OnLeftStickDown;
                @LeftStickDown.canceled += instance.OnLeftStickDown;
                @LeftStickLeft.started += instance.OnLeftStickLeft;
                @LeftStickLeft.performed += instance.OnLeftStickLeft;
                @LeftStickLeft.canceled += instance.OnLeftStickLeft;
                @LeftStickRight.started += instance.OnLeftStickRight;
                @LeftStickRight.performed += instance.OnLeftStickRight;
                @LeftStickRight.canceled += instance.OnLeftStickRight;
                @LeftStickButton.started += instance.OnLeftStickButton;
                @LeftStickButton.performed += instance.OnLeftStickButton;
                @LeftStickButton.canceled += instance.OnLeftStickButton;
                @LeftStickHorizontal.started += instance.OnLeftStickHorizontal;
                @LeftStickHorizontal.performed += instance.OnLeftStickHorizontal;
                @LeftStickHorizontal.canceled += instance.OnLeftStickHorizontal;
                @LeftStickVertical.started += instance.OnLeftStickVertical;
                @LeftStickVertical.performed += instance.OnLeftStickVertical;
                @LeftStickVertical.canceled += instance.OnLeftStickVertical;
                @LeftStick.started += instance.OnLeftStick;
                @LeftStick.performed += instance.OnLeftStick;
                @LeftStick.canceled += instance.OnLeftStick;
                @RightStickUp.started += instance.OnRightStickUp;
                @RightStickUp.performed += instance.OnRightStickUp;
                @RightStickUp.canceled += instance.OnRightStickUp;
                @RightStickDown.started += instance.OnRightStickDown;
                @RightStickDown.performed += instance.OnRightStickDown;
                @RightStickDown.canceled += instance.OnRightStickDown;
                @RightStickLeft.started += instance.OnRightStickLeft;
                @RightStickLeft.performed += instance.OnRightStickLeft;
                @RightStickLeft.canceled += instance.OnRightStickLeft;
                @RightStickRight.started += instance.OnRightStickRight;
                @RightStickRight.performed += instance.OnRightStickRight;
                @RightStickRight.canceled += instance.OnRightStickRight;
                @RightStickButton.started += instance.OnRightStickButton;
                @RightStickButton.performed += instance.OnRightStickButton;
                @RightStickButton.canceled += instance.OnRightStickButton;
                @RightStickHorizontal.started += instance.OnRightStickHorizontal;
                @RightStickHorizontal.performed += instance.OnRightStickHorizontal;
                @RightStickHorizontal.canceled += instance.OnRightStickHorizontal;
                @RightStickVertical.started += instance.OnRightStickVertical;
                @RightStickVertical.performed += instance.OnRightStickVertical;
                @RightStickVertical.canceled += instance.OnRightStickVertical;
                @RightStick.started += instance.OnRightStick;
                @RightStick.performed += instance.OnRightStick;
                @RightStick.canceled += instance.OnRightStick;
                @LeftBumper.started += instance.OnLeftBumper;
                @LeftBumper.performed += instance.OnLeftBumper;
                @LeftBumper.canceled += instance.OnLeftBumper;
                @RightBumper.started += instance.OnRightBumper;
                @RightBumper.performed += instance.OnRightBumper;
                @RightBumper.canceled += instance.OnRightBumper;
                @LeftTrigger.started += instance.OnLeftTrigger;
                @LeftTrigger.performed += instance.OnLeftTrigger;
                @LeftTrigger.canceled += instance.OnLeftTrigger;
                @RightTrigger.started += instance.OnRightTrigger;
                @RightTrigger.performed += instance.OnRightTrigger;
                @RightTrigger.canceled += instance.OnRightTrigger;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Start.started += instance.OnStart;
                @Start.performed += instance.OnStart;
                @Start.canceled += instance.OnStart;
            }

            private void UnregisterCallbacks(IAbuMapActions instance)
            {
                @ActionBottomRow1.started -= instance.OnActionBottomRow1;
                @ActionBottomRow1.performed -= instance.OnActionBottomRow1;
                @ActionBottomRow1.canceled -= instance.OnActionBottomRow1;
                @ActionBottomRow2.started -= instance.OnActionBottomRow2;
                @ActionBottomRow2.performed -= instance.OnActionBottomRow2;
                @ActionBottomRow2.canceled -= instance.OnActionBottomRow2;
                @ActionTopRow1.started -= instance.OnActionTopRow1;
                @ActionTopRow1.performed -= instance.OnActionTopRow1;
                @ActionTopRow1.canceled -= instance.OnActionTopRow1;
                @ActionTopRow2.started -= instance.OnActionTopRow2;
                @ActionTopRow2.performed -= instance.OnActionTopRow2;
                @ActionTopRow2.canceled -= instance.OnActionTopRow2;
                @DPadUp.started -= instance.OnDPadUp;
                @DPadUp.performed -= instance.OnDPadUp;
                @DPadUp.canceled -= instance.OnDPadUp;
                @DPadDown.started -= instance.OnDPadDown;
                @DPadDown.performed -= instance.OnDPadDown;
                @DPadDown.canceled -= instance.OnDPadDown;
                @DPadLeft.started -= instance.OnDPadLeft;
                @DPadLeft.performed -= instance.OnDPadLeft;
                @DPadLeft.canceled -= instance.OnDPadLeft;
                @DPadRight.started -= instance.OnDPadRight;
                @DPadRight.performed -= instance.OnDPadRight;
                @DPadRight.canceled -= instance.OnDPadRight;
                @LeftStickUp.started -= instance.OnLeftStickUp;
                @LeftStickUp.performed -= instance.OnLeftStickUp;
                @LeftStickUp.canceled -= instance.OnLeftStickUp;
                @LeftStickDown.started -= instance.OnLeftStickDown;
                @LeftStickDown.performed -= instance.OnLeftStickDown;
                @LeftStickDown.canceled -= instance.OnLeftStickDown;
                @LeftStickLeft.started -= instance.OnLeftStickLeft;
                @LeftStickLeft.performed -= instance.OnLeftStickLeft;
                @LeftStickLeft.canceled -= instance.OnLeftStickLeft;
                @LeftStickRight.started -= instance.OnLeftStickRight;
                @LeftStickRight.performed -= instance.OnLeftStickRight;
                @LeftStickRight.canceled -= instance.OnLeftStickRight;
                @LeftStickButton.started -= instance.OnLeftStickButton;
                @LeftStickButton.performed -= instance.OnLeftStickButton;
                @LeftStickButton.canceled -= instance.OnLeftStickButton;
                @LeftStickHorizontal.started -= instance.OnLeftStickHorizontal;
                @LeftStickHorizontal.performed -= instance.OnLeftStickHorizontal;
                @LeftStickHorizontal.canceled -= instance.OnLeftStickHorizontal;
                @LeftStickVertical.started -= instance.OnLeftStickVertical;
                @LeftStickVertical.performed -= instance.OnLeftStickVertical;
                @LeftStickVertical.canceled -= instance.OnLeftStickVertical;
                @LeftStick.started -= instance.OnLeftStick;
                @LeftStick.performed -= instance.OnLeftStick;
                @LeftStick.canceled -= instance.OnLeftStick;
                @RightStickUp.started -= instance.OnRightStickUp;
                @RightStickUp.performed -= instance.OnRightStickUp;
                @RightStickUp.canceled -= instance.OnRightStickUp;
                @RightStickDown.started -= instance.OnRightStickDown;
                @RightStickDown.performed -= instance.OnRightStickDown;
                @RightStickDown.canceled -= instance.OnRightStickDown;
                @RightStickLeft.started -= instance.OnRightStickLeft;
                @RightStickLeft.performed -= instance.OnRightStickLeft;
                @RightStickLeft.canceled -= instance.OnRightStickLeft;
                @RightStickRight.started -= instance.OnRightStickRight;
                @RightStickRight.performed -= instance.OnRightStickRight;
                @RightStickRight.canceled -= instance.OnRightStickRight;
                @RightStickButton.started -= instance.OnRightStickButton;
                @RightStickButton.performed -= instance.OnRightStickButton;
                @RightStickButton.canceled -= instance.OnRightStickButton;
                @RightStickHorizontal.started -= instance.OnRightStickHorizontal;
                @RightStickHorizontal.performed -= instance.OnRightStickHorizontal;
                @RightStickHorizontal.canceled -= instance.OnRightStickHorizontal;
                @RightStickVertical.started -= instance.OnRightStickVertical;
                @RightStickVertical.performed -= instance.OnRightStickVertical;
                @RightStickVertical.canceled -= instance.OnRightStickVertical;
                @RightStick.started -= instance.OnRightStick;
                @RightStick.performed -= instance.OnRightStick;
                @RightStick.canceled -= instance.OnRightStick;
                @LeftBumper.started -= instance.OnLeftBumper;
                @LeftBumper.performed -= instance.OnLeftBumper;
                @LeftBumper.canceled -= instance.OnLeftBumper;
                @RightBumper.started -= instance.OnRightBumper;
                @RightBumper.performed -= instance.OnRightBumper;
                @RightBumper.canceled -= instance.OnRightBumper;
                @LeftTrigger.started -= instance.OnLeftTrigger;
                @LeftTrigger.performed -= instance.OnLeftTrigger;
                @LeftTrigger.canceled -= instance.OnLeftTrigger;
                @RightTrigger.started -= instance.OnRightTrigger;
                @RightTrigger.performed -= instance.OnRightTrigger;
                @RightTrigger.canceled -= instance.OnRightTrigger;
                @Select.started -= instance.OnSelect;
                @Select.performed -= instance.OnSelect;
                @Select.canceled -= instance.OnSelect;
                @Start.started -= instance.OnStart;
                @Start.performed -= instance.OnStart;
                @Start.canceled -= instance.OnStart;
            }

            public void RemoveCallbacks(IAbuMapActions instance)
            {
                if (m_Wrapper.m_AbuMapActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IAbuMapActions instance)
            {
                foreach (var item in m_Wrapper.m_AbuMapActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_AbuMapActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public AbuMapActions @abuMap => new AbuMapActions(this);
        public interface IAbuMapActions
        {
            void OnActionBottomRow1(InputAction.CallbackContext context);
            void OnActionBottomRow2(InputAction.CallbackContext context);
            void OnActionTopRow1(InputAction.CallbackContext context);
            void OnActionTopRow2(InputAction.CallbackContext context);
            void OnDPadUp(InputAction.CallbackContext context);
            void OnDPadDown(InputAction.CallbackContext context);
            void OnDPadLeft(InputAction.CallbackContext context);
            void OnDPadRight(InputAction.CallbackContext context);
            void OnLeftStickUp(InputAction.CallbackContext context);
            void OnLeftStickDown(InputAction.CallbackContext context);
            void OnLeftStickLeft(InputAction.CallbackContext context);
            void OnLeftStickRight(InputAction.CallbackContext context);
            void OnLeftStickButton(InputAction.CallbackContext context);
            void OnLeftStickHorizontal(InputAction.CallbackContext context);
            void OnLeftStickVertical(InputAction.CallbackContext context);
            void OnLeftStick(InputAction.CallbackContext context);
            void OnRightStickUp(InputAction.CallbackContext context);
            void OnRightStickDown(InputAction.CallbackContext context);
            void OnRightStickLeft(InputAction.CallbackContext context);
            void OnRightStickRight(InputAction.CallbackContext context);
            void OnRightStickButton(InputAction.CallbackContext context);
            void OnRightStickHorizontal(InputAction.CallbackContext context);
            void OnRightStickVertical(InputAction.CallbackContext context);
            void OnRightStick(InputAction.CallbackContext context);
            void OnLeftBumper(InputAction.CallbackContext context);
            void OnRightBumper(InputAction.CallbackContext context);
            void OnLeftTrigger(InputAction.CallbackContext context);
            void OnRightTrigger(InputAction.CallbackContext context);
            void OnSelect(InputAction.CallbackContext context);
            void OnStart(InputAction.CallbackContext context);
        }
    }
}
